Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -37,9 +37,19 @@ jobs:
           password: ${{ secrets.DOCKERHUB_TOKEN }}
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
+      #Fixing the spaces/newlines and ensures lowercase
+      - name: Prepare image vars
+        run: |
+          DU=$(printf "%s" "${{ vars.DOCKER_USERNAME }}" | tr -d '[:space:]')
+          if [ -z "$DU" ]; then
+            echo "ERROR: Actions Variable DOCKER_USERNAME is not set." >&2
+            exit 1
+          fi
+          echo "DOCKER_USERNAME=$DU" >> $GITHUB_ENV
+
       - name: Build and push
         uses: docker/build-push-action@v6
         with:
           platforms: linux/amd64,linux/arm64
           push: true
-          tags: "sunglin675/assignment-8-part-2:latest"
+            ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
